# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8081
management:
  port: 54001
  security:
    enabled: false

#  health:
#    mail:
#      enabled: false
# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true


