# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8081

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: 123456
        url: jdbc:mysql://116.62.8.82:3306/tom_vip?useUnicode=true&characterEncoding=UTF-8
        username: tom_vip
        password: Vip123456
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

